# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Listasimple
else:
    import _Listasimple

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Nodo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    sig = property(_Listasimple.Nodo_sig_get, _Listasimple.Nodo_sig_set)

    def __init__(self, elemento):
        _Listasimple.Nodo_swiginit(self, _Listasimple.new_Nodo(elemento))

    def getElemento(self):
        return _Listasimple.Nodo_getElemento(self)
    __swig_destroy__ = _Listasimple.delete_Nodo

# Register Nodo in _Listasimple:
_Listasimple.Nodo_swigregister(Nodo)

class ListaSimple(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Listasimple.ListaSimple_swiginit(self, _Listasimple.new_ListaSimple())

    def vacio(self):
        return _Listasimple.ListaSimple_vacio(self)

    def insertarAlFrente(self, elemento):
        return _Listasimple.ListaSimple_insertarAlFrente(self, elemento)

    def insertarAlFinal(self, elemento):
        return _Listasimple.ListaSimple_insertarAlFinal(self, elemento)

    def eliminarAlFrente(self):
        return _Listasimple.ListaSimple_eliminarAlFrente(self)

    def eliminarAlFinal(self):
        return _Listasimple.ListaSimple_eliminarAlFinal(self)

    def mostrarLista(self):
        return _Listasimple.ListaSimple_mostrarLista(self)
    __swig_destroy__ = _Listasimple.delete_ListaSimple

# Register ListaSimple in _Listasimple:
_Listasimple.ListaSimple_swigregister(ListaSimple)



